language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
sudo: true
install:
  - pip install -r requirements.txt
script:
  - python tests.py
  - python -m pylint -E . --disable=R,C,W
  - python -m pylint classes/*.py --disable=R,C,W,too-many-function-args,import-error
